name: Java CI
on:
  push:
    branches:
      - master
      - '[4-9]+.[0-9]+.x'
      - '[3-9]+.[3-9]+.x'
  pull_request:
    branches:
      - master
      - '[4-9]+.[0-9]+.x'
      - '[3-9]+.[3-9]+.x'
  workflow_dispatch:

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  build:
    permissions:
      contents: read  #  to fetch code (actions/checkout)
      checks: write  #  to publish result as PR check (scacap/action-surefire-report)

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '14']
    env:
      WORKSPACE: ${{ github.workspace }}
      GRADLE_OPTS: -Xmx1500m -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Set up JDK
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Run Tests
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        id: tests
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2
        with:
          arguments: check
        env:
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER }}
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY }}
      - name: Run Build
        if: github.event_name == 'push'
        id: build
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER }}
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY }}
        with:
          arguments: build
      - name: Publish Test Report
        if: steps.build.outcome == 'failure' || steps.tests.outcome == 'failure'
        uses: scacap/action-surefire-report@be8172cc301d1805659f46260815db3e9ad574b2 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Publish to repo.grails.org
        id: publish
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2
        if: steps.build.outcome == 'success' && github.event_name == 'push' && matrix.java == '8'
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        with:
          arguments: -Dorg.gradle.internal.publish.checksums.insecure=true publish
      - name: Extract branch name
        if: steps.publish.outcome == 'success' && github.event_name == 'push' && matrix.java == '8'
        id: extract_branch
        run: echo ::set-output name=value::${GITHUB_REF:11}
      - name: Create Snapshot Message for the Workflow Dispatch
        if: steps.publish.outcome == 'success' && github.event_name == 'push' && matrix.java == '8'
        id: dispatch_message
        run: echo ::set-output name=value::{\"message\":\"New Core Snapshot $(date) - $GITHUB_SHA\"}
      - name: Invoke the Java CI workflow in Grails Functional Tests
        if: steps.publish.outcome == 'success' && github.event_name == 'push' && matrix.java == '8'
        uses: benc-uk/workflow-dispatch@798e70c97009500150087d30d9f11c5444830385 # tag=v1.2
        with:
          workflow: Java CI
          repo: grails/grails-functional-tests
          ref: ${{ steps.extract_branch.outputs.value }}
          token: ${{ secrets.GH_TOKEN }}
          inputs: ${{ steps.dispatch_message.outputs.value }}
